### ISSUE TITLE
업데이트 이후 에러 발생

### ISSUE THREAD

**Issue by limjdsn** [limerainne/mp3tag-ws-bugs#14]
안녕하세요? 덕분에 잘 사용하고 있습니다.
오늘 mp3tag를 3.22(윈도우 버전입니다)로 업데이트하고 나니 예전에는 없던 에러가 발생합니다.
https://ibb.co/q9mcpLF
신텍스 에러라 하네요.
확인 한 번 부탁드립니다.
감사합니다.

**Comment by limerainne** [comment]
안녕하세요,

알려주셔서 감사합니다!
말씀대로 스크립트에 문법 오류를 만들었었고, Mp3tag v3.22에서야 오류가 드러났습니다.

아직 "Release" 메뉴에 새 버전을 만들지는 않았습니다.
최신 버전을 직접 다운로드하셔서 사용하시거나
(저장소 홈 화면 상단의 "Code" 버튼 > "Download ZIP" 버튼을 사용하실 것 같습니다)
조금 더 기다려주셔서 제가 "Release" 메뉴에 만들 버전을 사용하셔도 좋을 것 같습니다.

-----
 *  고치기 전
    - 'RegexpReplace' 명령 끝에 "1"을 붙였습니다.
https://github.com/limerainne/mp3tag-ws-bugs/blob/44168bca9d9a4664994caed8e79a5675c4651405/Bugs%23Common_AlbumPage.inc#L90

 * 고친 후
    - "1"을 지워서, 올바르게 'RegexpReplace' 명령을 사용했습니다.
https://github.com/limerainne/mp3tag-ws-bugs/blob/d564f197a744a623e18b80fdffa73e9b3291caf8/Bugs%23Common_AlbumPage.inc#L90
