### ISSUE TITLE
태그를 가져올때 생기는 문제

### ISSUE THREAD

**Issue by UzuCore** [limerainne/mp3tag-ws-bugs#16]
윈도우11 에서 테스트했습니다.
2번 트랙 '(여자)아이들 - Allergy' 파일로 테스트하면 아무리 시도해도
1번 트랙 '(여자)아이들 - 퀸카 (Queencard)'의 태그정보를 가져옵니다.
버전 문제일 수 있다고 생각하여 2-3년전 mp3tag를 구해서 실행해도 마찬가지의 결과네요.
확인 좀 부탁드려도 될까요?
소중한 프로그램 감사합니다.

**Comment by UzuCore** [comment]
사용방법이 문제였네요.
닫을게요

**Comment by limerainne** [comment]
정보를 앨범 단위로 가져오므로, 음악 파일을 해당하는 트랙 순서에 맞춰주는 일이 필요했습니다. 그것을 놓치신 사례인 것 같습니다.
감사합니다.
