### ISSUE TITLE
언젠가부터 앨범 및 곡 정보를 검색하면 곡명과 아티스트명이 갱신되지 않습니다.

### ISSUE THREAD

**Issue by kdj0692** [limerainne/mp3tag-ws-bugs#17]
또한 최신버전에서는  parameter 3가 누락되었다고 아예 작동되지가 않네요.

**Comment by limerainne** [comment]
다음 버전에서 문제가 해결되었는지 확인해보세요: [v0.4.14](https://github.com/limerainne/mp3tag-ws-bugs/releases/tag/v0.4.14)
Mp3tag v3.22부터 명령어 하나가 개정되어서 문제가 있었고, [v0.4.12](https://github.com/limerainne/mp3tag-ws-bugs/releases/tag/v0.4.12)에서 고칠 수 있었습니다.

**Comment by limerainne** [comment]
업데이트 후 다른 분들께서 된다시니, 해결된 것으로 보여 닫겠습니다.
