### ISSUE TITLE
0: SSL Error: WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED failed to check revocation status.

### ISSUE THREAD

**Issue by kdj0692** [limerainne/mp3tag-ws-bugs#19]
서버 연결 오류: https://music.bugs.co.kr
> 0: SSL Error: WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED failed to check revocation status.

**Comment by limerainne** [comment]
오류 메시지를 곧이곧대로 읽으면 "인증서 검증 실패"인데요,

금일 제 PC에서 잘 되며 (Win11 23H2 / Mp3tag v3.28), 벅스 홈페이지도 잘 열리고 있습니다. 이에 적어도 현재는 본 스크립트의 문제나 Mp3tag 프로그램, 벅스 홈페이지의 문제가 있지는 않은 것 같습니다.

대신 문제를 겪으신 당시 벅스 서버에 일시적인 인증서 문제가 있었다거나,
또는 사용하시는 PC나 인터넷 환경의 문제를 의심해보아야 할 것 같습니다.

그럼에도 문제가 지속되신다면 이슈를 다시 열어주시고 보다 자세히 상황을 알려주시면 감사하겠습니다.
